package com.stimply.spoticlone.domain.util

object SongsConstants {
    const val ACTION_PLAYER_STATE_IDLE = "ACTION_PLAYER_STATE_IDLE"
    const val ACTION_PLAYER_STATE_BUFFERING = "ACTION_PLAYER_STATE_BUFFERING"
    const val ACTION_PLAYER_STATE_READY = "ACTION_PLAYER_STATE_READY"
    const val ACTION_PLAYER_STATE_ENDED = "ACTION_PLAYER_STATE_ENDED"
    const val ACTION_PLAYBACK_RESUMPTION = "ACTION_PLAYBACK_RESUMPTION"
    const val LOG_TAG = "SPOTICLONE_DEBUG_TAG"
    const val NOTIFICATION_CLICK_REQUEST_ID = 3
}